name: amber-bash
icon: assets/amber.png
title: Amber
base: core24
version: '0.3.2-alpha'
summary: Amber the programming language compiled to bash
description: |
  Programming language that compiles to Bash. It's a high level programming language that makes it easy to create shell scripts.
  It's particularly well suited for cloud services.
contact: https://discord.com/invite/cjHjxbsDvZ
source-code: https://github.com/Ph0enixKM/Amber
issues: https://github.com/Ph0enixKM/Amber/issues
website: https://amber-lang.com/
grade: stable
confinement: classic
compression: lzo

parts:
  amber:
    plugin: rust
    source: .
    build-attributes:
      - enable-patchelf


apps:
  amber:
    command: bin/amber
