name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust build and tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Cache dependencies installed with cargo
      uses: actions/cache@v3
      with:
        path: |
            ./target/deps
            ~/.cargo
        key: rust-${{ hashFiles('Cargo.lock') }}
        restore-keys: rust-${{ hashFiles('Cargo.lock') }}
    - name: Run all tests
      run: cargo test --verbose
